language: ruby
sudo: false
cache: bundler
addons:
  apt:
    packages:
    - libhiredis-dev
  postgresql: '9.3'
services:
  - redis-server
rvm:
  - 2.2
env: DB=postgres CI=1
bundler_args: --without development debug
before_script:
  - cp config/database.yml.ci config/database.yml
  - cp .env.example .env
  - bundle exec rake db:setup
script: bundle exec rake
deploy:
  provider: script
  script: bin/deploy
  on:
    branch: master
