# Commit is automatically performed by Solr every 10s OR 1000 new objects.
# See ../solr/conf/solrconfig.xml around line 212
# This greatly increases response of app at the cost of how 'fresh' the index is.
auto_commit_after_request: false 

production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/
test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/
    
